include ../make.rule

TARGET	= testmalloc testmprotect teststruct test_stack test_struct_init testcontainer_of testreadexec testSimpleSection test_union testcoredump get_sp testdtor testheapmaps testmaps 

all : $(TARGET)
